import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.scss";
import { LangProps } from "@/Utils";

type RootLayoutProps = {
	children: React.ReactNode;
} & LangProps;

const roboto = Roboto({ subsets: ["latin"], weight: "500" });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
	params: { lang },
}: RootLayoutProps) {
	return (
		<html lang={lang}>
			<body className={roboto.className}>{children}</body>
		</html>
	);
}
